### ISSUE TITLE
Help wanted!  How to use hop.nvim with command `d`?

### ISSUE THREAD

**Issue by gaoqiangks** [smoka7/hop.nvim#90]
For example, I want `df` to delete until a specific char. I searched the doc, nothing is said about how to use `hop.nvim`  with delete.  How to achieve this?

**Comment by f73** [comment]
It is under Features on front page:

- Use it with commands like v, d, c, y to visually select/delete/change/yank up to your new cursor position.

So, having word "**command**" as an example, to delete from **c** to 2nd **m**, you would press **d** followed by **s** followed by character that appears instead of 2nd letter m. Just do a brief pause after pressing v, d, c, y
